### ISSUE TITLE
Error in `StretchMove` proposals when `nwalkers` is odd

### ISSUE THREAD

**Issue by rjrosati** [mikekatz04/Eryn#10]
I've been getting an error occasionally when running the sampler in medium to large parameter spaces, depending on the values of `nwalkers`, `ndims`, and `ntemps`. There's some kind of off-by-one error in `moves/red_blue.py`, but I haven't figured out exactly what the combinatorics of it are. Here's a minimal working example:

```python
from eryn.prior import ProbDistContainer, uniform_dist
from eryn.moves import StretchMove
from eryn.ensemble import EnsembleSampler
import numpy as np
ndim = 7
nwalkers = 25
ntemps = 8

def log_like_fn(x, mu, invcov):
    diff = x - mu
    return -0.5 * (diff * np.dot(invcov, diff.T).T).sum()

means = np.zeros(ndim)
cov = np.diag(np.ones(ndim))
invcov = np.linalg.inv(cov)

lims = 5.0
priors_in = {i: uniform_dist(-lims+means[i], lims+means[i]) for i in range(ndim)}
priors = {'model_0': ProbDistContainer(priors_in)}

ensemble = EnsembleSampler(nwalkers,ndim,log_like_fn,priors,args=[means,invcov],
                           moves = [
                               (StretchMove(),1.0),
                               ],tempering_kwargs={'ntemps':ntemps})

theta0 = priors['model_0'].rvs(size=(ntemps,nwalkers,))
result = ensemble.run_mcmc(theta0,1000,burn=200,progress=True,thin_by=2)
```

And here's the error I'm getting:
```
Traceback (most recent call last):
  File "/Users/rjrosati/code/sgwb-data-analysis/issue_eryn.py", line 27, in <module>
    result = ensemble.run_mcmc(theta0,1000,burn=200,progress=True,thin_by=2)
  File "/Users/rjrosati/opt/anaconda3/envs/ldc/lib/python3.10/site-packages/eryn/ensemble.py", line 991, in run_mcmc
    for results in self.sample(initial_state, iterations=burn, **burn_kwargs):
  File "/Users/rjrosati/opt/anaconda3/envs/ldc/lib/python3.10/site-packages/eryn/ensemble.py", line 884, in sample
    state, accepted_out = move.propose(model, state)
  File "/Users/rjrosati/opt/anaconda3/envs/ldc/lib/python3.10/site-packages/eryn/moves/red_blue.py", line 156, in propose
    fixed_inds_shaped = all_inds[~S1].reshape(ntemps, nwalkers_here)
ValueError: cannot reshape array of size 96 into shape (8,13)
```
I'm running the latest main branch commit of Eryn, e683f302e61ab110139be2fb95a1c1d57972656b .
Here's a small table of combinations I've tried, in case @mikekatz04 or someone else spots a pattern :)
| ntemps | nwalkers | ndim | works? |
|--------|----------|------|--------|
| 10     | 63       | 9    | ❌      |
| 11     | 63       | 9    | ❌      |
| 9      | 63       | 9    | ❌      |
| 9      | 70       | 10   | ✅      |
| 1      | 77       | 11   | ❌      |
| 1      | 84       | 12   | ✅      |
| 1      | 83       | 12   | ❌      |
| 1      | 84       | 13   | ✅      |
| 1      | 83       | 13   | ❌      |

Actually now that I look at the table, I think the problem only happens when `nwalkers` is odd.

**Comment by mikekatz04** [comment]
Fixed in 1.1.4
