### ISSUE TITLE
Possible error in `swap_acceptance_fraction`

### ISSUE THREAD

**Issue by CaseyMcGrath** [mikekatz04/Eryn#15]
Hi Michael, just wanted to report two things at the moment regarding swap fractions:

1. In the eryn documentation [starting at this line](https://mikekatz04.github.io/Eryn/html/user/ensemble.html#:~:text=property-,acceptance_fraction,-%EF%83%81), something appears redundant - both `acceptance_fraction` and `swap_acceptance_fraction` have identical descriptions, and so do `rj_acceptance_fraction` and `rj_swap_acceptance_fraction`.  If both of these are being saved and stored then you may be creating larger outputs in memory/file space than actually needed?
2. I often find when I run the sampler then output the temperature swap fraction via `ensemble.swap_acceptance_fraction.mean()`, I get a value > 1.

**Comment by mikekatz04** [comment]
Should be fixed now in version 1.1.7
