### ISSUE TITLE
Thin/burn calculation from autocorrelation times typically fails with Reversible Jump

### ISSUE THREAD

**Issue by CaseyMcGrath** [mikekatz04/Eryn#16]
When using RJMCMC, trying to compute the thin and burn values from the autocorrelation time typically fails because of how NaNs get stored in the chain file.  E.g.

> loaded_data = HDFBackend('/path/to/directory/file.h5', name='run')
> loaded_data.get_autocorr_thin_burn()

returns the error:
> ValueError: cannot convert float NaN to integer

because `loaded_data.get_autocorr_time()` contains NaNs.

**Comment by CaseyMcGrath** [comment]
Ok so after a side conversation with Michael, autocorrelation times aren't meaningful when using parallel tempering and/or reversible jump.

So my thought/suggestion might be to consider this an "enhancement" suggestion, and add a flag or error message into `.get_autocorr_thin_burn()` and any other similar functions if someone tries running them when the `ntemps > 1`, and/or `nleaves_max > 1`.  And maybe add this into the eryn documentation/tutorial as a brief disclaimer for those who may not be as familiar with autocorrelation.

**Comment by mikekatz04** [comment]
Will do in near future.

**Comment by mikekatz04** [comment]
Adjusted in 1.1.7
