### ISSUE TITLE
check the multipletry.py moves in RJ

### ISSUE THREAD

**Issue by martinaAEI** [mikekatz04/Eryn#17]
check that the random generator  is propagated correctly among the different stages of the code
    
add this part of the code in lines 710 to 721
#########
     if len(inds_reverse_rj) > 0:
            # calculate information for the reverse
            lp_reverse_here = self.current_model.compute_log_prior_fn(
                temp_reverse_coords, inds=temp_reverse_inds
            )[0]
            ll_reverse_here = self.current_model.compute_log_like_fn(
                temp_reverse_coords, inds=temp_reverse_inds, logp=lp_here
            )[0]

            # fill the here values
            ll_here[inds_reverse_rj] = ll_reverse_here
            lp_here[inds_reverse_rj] = lp_reverse_here
###############

**Comment by mikekatz04** [comment]
This is fixed in 1.1.7
