### ISSUE TITLE
`self.iter` not being updated in `GroupMove`

### ISSUE THREAD

**Issue by antcc** [mikekatz04/Eryn#18]
Is there a specific reason why the updating `self.iter += 1` is not being performed in the `propose` or `setup` method of `GroupMove`? I guess it could be implemented by subclasses but it is not documented anywhere, and it seems like an odd place for this updating mechanism to be. Maybe it got lost along the way in the refactoring?

**Comment by mikekatz04** [comment]
This got lost along the way. Fixed in version 1.1.7.
