### ISSUE TITLE
Group stretch move issue when using gibbs_sampling_setup

### ISSUE THREAD

**Issue by asantini29** [mikekatz04/Eryn#22]
When using the `GroupStretchMove` (or any proposal whose parent class is the `GroupMove`, I think) only on some of the branches using the `gibbs_sampling_setup` keyword, the order of the branches in the newly proposed coordinates does not follow the supposed one. As an example, I tried to run with 5 branches using the `GroupStretchMove` only in the fifth. The order of the branches in the newly proposed coordinates is 5, 0, 1, 2, 3, 4 instead of 0, 1, 2, 3, 4,5. I suspect the issue is the absence of a call to `self.ensure_ordering` in `group.py`

**Comment by mikekatz04** [comment]
Fixed in version 1.1.12 (3dfcc59)
