### ISSUE TITLE
Possible inconsistency with use of CuPy in EnsembleSampler.run_mcmc()

### ISSUE THREAD

**Issue by AminBoumerdassi** [mikekatz04/Eryn#24]
When setting up the priors, I do ```ProbDistContainer(xyz_priors, use_cupy = use_gpu)``` where ```use_gpu=True```. The logpdf method is expected to give a numpy array however on line 280 of ```priors.py```, the output array of priors is initialised as ```prior_vals = xp.zeros(x.shape[0])``` which in this case is a Cupy array.

When running the mcmc, this causes a mismatch of numpy and cupy arrays. This happens because in the ```compute_log_prior``` method of ensemble.py, the output of priors on line 1171 is initialised as ```prior_out = np.zeros((ntemps * nwalkers))``` rather than ```xp.zeros((ntemps * nwalkers))```.

I'm unsure what the intended behaviour is meant to be. Are the outputs of the prior calculations exclusively meant to be numpy arrays, or should it be possible to run the MCMC chain entirely with CuPy?

**Comment by mikekatz04** [comment]
I fixed this in ff36c66. It adds an option of `return_gpu` and now should account for that properly inside the `ProbDistContainer`.
