### ISSUE TITLE
Problem when restarting from backend

### ISSUE THREAD

**Issue by alextoub7** [mikekatz04/Eryn#6]
When reading the last state in the backend object, the order of the items is not necessarily the same as in branc_names. This lead to an dimensional incompatibility problem in ensemble.py (line 706), because it is not comapring the dimensionality of the same branches.
This could be solved by using a dictionary for ndims instead of a list.

**Comment by mikekatz04** [comment]
Fixed. Everything is built in terms of dictionaries now, but still compatible with list entries.
