### ISSUE TITLE
Bugs in multiple try, generating rj leaves and passing multiple rj moves

### ISSUE THREAD

**Issue by alextoub7** [mikekatz04/Eryn#7]
In the multiple try, line 706 of multipletry.py, the codes goes through all the keys and reshapes the array to the shape ntemps * nwalkers, nleaves_max, the problem is that nleaves_max is read from earlier, line 622, and corresponds to the max number of leaves of the group it is trying to change. If the maximum number of leaves for each branch is not the same this leads to an error.
I fixed it by changing nleaves_max into nleaves_max_temp, which is read line 691 and corresponds to the max number of leaves of the correct branch.

In priors.py, when using a single prior for all the parameters of a group, e.g. multivariate normal, the adjust inds makes the new points prior_i.rvs(size=size)[adjust_inds] have shape (npts,1,ndim) and we get a format error on line ~380. 
I fixed it that by adding an if: 
if len(self.priors)<self.ndim:
  out[inds_in] = prior_i.rvs(size=size)[adjust_inds][:,0]
else:
  out[inds_in] = prior_i.rvs(size=size)[adjust_inds]

When passing multiple rj moves I get two problems:

1) if i pass with weights rj_moves=[(rj_move1,0.7),(rj_move2,0.3)], I get the error: TypeError: can only concatenate list (not "tuple") to list.

2) When passing rj_moves=[rj_move1,rj_move2] and backend is not None, I get an AssertError from line 681 of hdfbackend.py because the equality len(moves_accepted_fraction) == len(self.move_keys) is not satisfied.

**Comment by mikekatz04** [comment]
I think this was all fixed. Please let me know if you find other issues.
