### ISSUE TITLE
Corner module not found in Eryn

### ISSUE THREAD

**Issue by NazeelaAimen** [mikekatz04/Eryn#9]
Hi,

I installed Eryn and tried to execute a tutorial. I got an error: 

`ModuleNotFoundError: No module named 'corner'.`

I searched for it in the repository but couldn't find it. Please let me know how to resolve this. 

Thank you.

**Comment by rjrosati** [comment]
Hi,

I think the package you need is corner.py . You can install it with `pip install corner`. I don't think it has been added as a dependency of Eryn, but the tutorials do use it.
